### ISSUE TITLE
Threads not closed properly after analysis

### ISSUE THREAD

**Issue by step-xiaoyu-ka** [RUB-SysSec/EthBMC#5]
Hi, I tried the easiest way to use EthBMC `./target/release/ethbmc examples/rubixi/rubixi.yml`, but it reported errors. Please give me some hints.
```
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs:660:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs:660:9
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs:660:9
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs:660:9
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalidattempted to leave type `internal::Local` uninitialized, which is invalid', ', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs/rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs::660660::99

[2021-07-05][03:00:51][esvm][INFO] =========================================================
[2021-07-05][03:00:51][esvm][INFO] Starting first round.
[2021-07-05][03:00:51][esvm][INFO] =========================================================
thread 'main' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs:660:9
thread '<unnamed>' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/mem/mod.rs:660:9
thread 'main' panicked at 'Threads not closed properly after analysis: Any { .. }', esvm/src/se/symbolic_graph.rs:211:18

thread panicked while panicking. aborting.
```

**Comment by Joool** [comment]
We have updated the [crossbeam](https://github.com/crossbeam-rs/crossbeam) version. Can you rebuild and check if that fixes your issue?

**Comment by step-xiaoyu-ka** [comment]
Thanks for your answer. It has been solved. But after finding potential attack states,  the analyzation is terminated by the panic`'couldn't spawn evm: entity not found', evmexec/src/evm.rs:101:25`. I know that `evmexec` expects a valid geth evm instance in my path. `geth 1.8.27-stable` is available both in `/usr/bin`and `/usr/local/bin`, but not enough. Does that mean running an Ethereum node?

**Comment by Joool** [comment]
No, the only requirement is that the `evm` executable (included in the [Geth & Tools Bundle](https://geth.ethereum.org/downloads/)) is in you PATH.
Both of the locations you listed should work, but you can check with `echo $PATH`.

**Comment by step-xiaoyu-ka** [comment]
`evm` executable, that's the problem. Everything is going well now. Thanks for help and for your impressive paper.

**Comment by Joool** [comment]
I have added a comment to the README to better specify this.
